id: cassandra-node-emptydir
kind: Template
apiVersion: v1
name: 'Hawkular Cassandra Node Template: Emphemeral Storage'
description: Configures a Cassandra Node with ephemeral storage.
metadata:
  name: cassandra-node-emptydir
  labels:
    metrics-infra: cassandra
parameters:
- description: If this Cassandra node should be the 'master' node.
  name: CASSANDRA_SERVICE
  value: 'false'
- description: If this Cassandra node should be the 'master' node.
  name: MASTER
  value: 'false'
- description: The node number for the Cassandra cluster.
  name: NODE
  required: true
objects:
- apiVersion: v1
  kind: ReplicationController
  metadata:
    name: cassandra-${NODE}
    labels:
      metrics-infra: cassandra
      name: cassandra
      type: cassandra
  spec:
    selector:
      name: cassandra-${NODE}
    replicas: 1
    template:
      version: v1
      metadata:
        labels:
          metrics-infra: cassandra
          name: cassandra-${NODE}
          type: cassandra
      spec:
        containers:
        - image: 172.30.188.59:5000/yepeng/origin-metrics
          name: cassandra-${NODE}
          ports:
          - name: cql-port
            containerPort: 9042
          - name: thift-port
            containerPort: 9160
          - name: tcp-port
            containerPort: 7000
          - name: ssl-port
            containerPort: 7001
          command:
          - "/opt/apache-cassandra/bin/cassandra-docker.sh"
          - "--cluster_name=metrics"
          - "--data_volume=/cassandra_data"
          env:
          - name: CASSANDRA_MASTER
            value: "${MASTER}"
          - name: CASSANDRA_SERVICE
            value: "${CASSANDRA_SERVICE}"
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          volumeMounts:
          - name: cassandra-data
            mountPath: "/cassandra_data"
          readinessProbe:
            exec:
              command:
              - "/opt/apache-cassandra/bin/cassandra-docker-ready.sh"
        volumes:
        - name: cassandra-data
          emptyDir: {}
