id: cassandra-services
kind: Template
apiVersion: v1
name: Hawkular Cassandra Services
description: Configures the Cassandra services for Hawkular Metrics support.
metadata:
  name: cassandra-services
  labels:
    metrics-infra: cassandra
objects:
- apiVersion: v1
  kind: Service
  metadata:
    name: cassandra
    labels:
      metrics-infra: cassandra
      name: cassandra
  spec:
    selector:
      type: cassandra
    ports:
    - name: cql-port
      port: 9042
      targetPort: cql-port
    - name: thift-port
      port: 9160
      targetPort: thift-port
    - name: tcp-port
      port: 7000
      targetPort: tcp-port
    - name: ssl-port
      port: 7001
      targetPort: ssl-port
- apiVersion: v1
  kind: Service
  metadata:
    name: cassandra-nodes
    labels:
      metrics-infra: cassandra
      name: cassandra
  spec:
    selector:
      type: cassandra
    portalIP: None
    ports:
    - name: cql-port
      port: 9042
    - name: thift-port
      port: 9160
    - name: tcp-port
      port: 7000
    - name: ssl-port
      port: 7001
